
#--------------------------------------------------------------
# vim core 

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kana/vim-submode'

#--------------------------------------------------------------
# vim appearance

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#--------------------------------------------------------------
# editting

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'tyru/operator-camelize.vim'
depends = 'kana/vim-operator-user'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'rhysd/vim-clang-format'

#--------------------------------------------------------------
# find files

[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'Shougo/ddu-source-register'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'

[[plugins]]
repo = 'Shougo/ddu-column-filename'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'

[[plugins]]
repo = 'mileszs/ack.vim'

#--------------------------------------------------------------
# git

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#--------------------------------------------------------------
# go

[[plugins]]
repo = 'mattn/vim-goimports'

#--------------------------------------------------------------
# fzf

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = '/usr/local/opt/fzf'

[[plugins]]
repo = '/usr/local/opt/fzf'
if = 'isdirectory("/usr/local/opt/fzf")'

#--------------------------------------------------------------
# vim-lsp

[[plugins]]
repo='vim-denops/denops.vim'

[[plugins]]
repo='Shougo/pum.vim'

[[plugins]]
repo='prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

#--------------------------------------------------------------
# test

[[plugins]]
repo = 'vim-test/vim-test'

[[plugins]]
repo = 'tpope/vim-dispatch'

#--------------------------------------------------------------
# terraform

[[plugins]]
repo = 'hashivim/vim-terraform'

#--------------------------------------------------------------
# php

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

