[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo='natebosch/vim-lsc'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'

#--------------------------------------------------------------
# vim-lsp

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = '/usr/local/opt/fzf'

[[plugins]]
repo = '/usr/local/opt/fzf'
if = 'isdirectory("/usr/local/opt/fzf")'

[[plugins]]
repo = '~/.fzf'
if = 'isdirectory(expand("~/.fzf"))'

#--------------------------------------------------------------
# vim-lsp

[[plugins]]
repo='prabirshrestha/async.vim'

[[plugins]]
repo='prabirshrestha/asyncomplete.vim'

[[plugins]]
repo='prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo='prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

#--------------------------------------------------------------
# terraform

[[plugins]]
repo = 'hashivim/vim-terraform'

#--------------------------------------------------------------
# php

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'
