[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'tpope/vim-abolish'

