
#--------------------------------------------------------------
# vim core 

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kana/vim-submode'

#--------------------------------------------------------------
# vim appearance

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#--------------------------------------------------------------
# editting

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'tyru/operator-camelize.vim'
depends = 'kana/vim-operator-user'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'rhysd/vim-clang-format'

#--------------------------------------------------------------
# find files

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'mileszs/ack.vim'

#--------------------------------------------------------------
# git

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#--------------------------------------------------------------
# go

[[plugins]]
repo = 'mattn/vim-goimports'

#--------------------------------------------------------------
# fzf

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = '/usr/local/opt/fzf'

[[plugins]]
repo = '/usr/local/opt/fzf'
if = 'isdirectory("/usr/local/opt/fzf")'

[[plugins]]
repo = '~/.fzf'
if = 'isdirectory(expand("~/.fzf"))'

#--------------------------------------------------------------
# vim-lsp

[[plugins]]
repo='Shougo/ddc.vim'

[[plugins]]
repo='vim-denops/denops.vim'

[[plugins]]
repo='Shougo/pum.vim'

[[plugins]]
repo='Shougo/ddc-around'

[[plugins]]
repo='LumaKernel/ddc-file'

[[plugins]]
repo='Shougo/ddc-matcher_head'

[[plugins]]
repo='Shougo/ddc-sorter_rank'

[[plugins]]
repo='Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo='shun/ddc-vim-lsp'

[[plugins]]
repo='matsui54/ddc-ultisnips'

[[plugins]]
repo='prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

#--------------------------------------------------------------
# test

[[plugins]]
repo = 'vim-test/vim-test'

[[plugins]]
repo = 'tpope/vim-dispatch'

#--------------------------------------------------------------
# terraform

[[plugins]]
repo = 'hashivim/vim-terraform'

#--------------------------------------------------------------
# php

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

